### ISSUE TITLE
clarify status & relationship with gitlab/SKAO

### ISSUE THREAD

**Issue by adriaanph** [ska-sa/katpoint#79]
@ludwigschwardt  
https://github.com/ska-sa/katpoint/releases/tag/v0.9 was cloned as https://gitlab.com/ska-telescope/katpoint/-/tags/v0.9, but since then the two repositories have had independent commits.

there seems to be periodic merges from github to gitlab (the last synch on v0.10 via SPAZA-297) but not the other way. in particular, it seems like the "astropy implementation" only exists in the gitlab project?

i have a strong suspicion that this github project should be flagged as "no longer under active development". please confirm and add a statement on the status in the main README.

**Comment by adriaanph** [comment]
i have only just discovered the gitlab repo last week "by accident", and saw katpoint just this afternoon. i'll have to find out what the strategy is for what stays in github and what goes in gitlab. regardless, it looks like it'll be necessary to raise general awareness levels within SARAO for the foreseeable future rather than to assume people know about it.

**Comment by ludwigschwardt** [comment]
That's a fortunate accident then 😁

The ~~short~~ long of it is: in 2019 David Terrett and I ported katpoint from PyEphem to Astropy under the auspices of SKAO. Since SKAO uses katpoint (in the TMC) it seemed better to start a new repo under GitLab within their framework. There was a brief thought of calling it `katpoint2` à la `spead2` and `corr2`, but Simon liked `katpoint` better. This sealed our fate, making it hard to test side-by-side and to upgrade gracefully 🙂 

The GitLab work will be released "soon" as katpoint 1.0 - and promptly break everyone's code, including our own 😅 We are still busy porting our pipelines before that can happen. I hope to give some advance warning, especially since I now notice ["Used by 43"](https://github.com/ska-sa/katpoint/network/dependents) and not everyone at SARAO... The latest GitLab release is 1.0a2 if you want to test it.

I'm going to freeze this repo at version 0.10 if at all possible.

**Comment by adriaanph** [comment]
thanks, i've just tried 1.02a and it broke my code in a few different ways (i've been taking advantage of "internal" secrets). but i guess this change is inevitable....

**Comment by ludwigschwardt** [comment]
Also, just be aware that the future 1.0a3 will break a few more things, especially around projections and refraction. That’s the beauty of alpha releases - they allow total freedom for remodelling your software after each release. 😁
